

**Q1-1**: Write a program that create a dataframe from the data.

**Q1-2:** Select people that are psychologist or teacher and their number of cars is greater than their family size.

**Q1-3:** Select people who have at most 2 family members and at least 1 car.

**Q1-4:** Write a code that get number of unique jobs in this dataset.





In [ ]:
import pandas as pd

data = {"name": ["Joseph", "Jacob", "Sam", "Jesee", "Ryan", "Lisa", "Lee"],
        "job": ["teacher", "psychologist", "data scientist", "software developer", "psychologist", "psychologist", "teacher"],
        "family_size": [3, 2, 1, 4, 2, 3, 2],
        "num_cars": [3, 1, 1, 2, 2, 4, 1]}

In [ ]:
# Type your solution here
#Q1-1
frame = pd.DataFrame(data, columns = ["name", "job", "family_size", "num_cars"], index=["one", "two", "three", "four", "five", "six", "seven"])
print(frame)

         name                 job  family_size  num_cars
one    Joseph             teacher            3         3
two     Jacob        psychologist            2         1
three     Sam      data scientist            1         1
four    Jesee  software developer            4         2
five     Ryan        psychologist            2         2
six      Lisa        psychologist            3         4
seven     Lee             teacher            2         1


In [ ]:
#Q1-2
frame[((frame["job"] == "teacher") | (frame["job"] == "psychologist")) & (frame["num_cars"] > frame["family_size"])]

name           job  family_size  num_cars
six  Lisa  psychologist            3         4

In [ ]:
#Q1-3
frame[(frame["family_size"] <= 2) & (frame["num_cars"] >= 1)]

name             job  family_size  num_cars
two    Jacob    psychologist            2         1
three    Sam  data scientist            1         1
five    Ryan    psychologist            2         2
seven    Lee         teacher            2         1

In [ ]:
#Q1-4

result = pd.value_counts(data["job"])
print(result)


psychologist          3
teacher               2
data scientist        1
software developer    1
dtype: int64


**Q2. Lets consider you have two series like the below cell. Compute the mean of weights of each fruit.**

In [ ]:
import numpy as np
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))

In [ ]:
# Type your solution here
results = weights.groupby(fruit).mean()

print(results)

apple     6.750000
banana    5.000000
carrot    4.333333
dtype: float64


**Q3. Consider the below course_name array:**

**Q3-1**: Write a NumPy program to get the indices of the sorted elements of **course_name** array.

**Q3-2:** Write numpy code to check whether each element of **course_name** array starts with "P".


In [ ]:
import numpy as np
course_name = np.array(['Python', 'JS', 'examples', 'PHP', 'html'])

In [ ]:
# Type your solution here
#Q3-1

indice = np.argsort(course_name)
print(indice)

[1 3 0 2 4]


In [ ]:
Pstart = np.char.startswith(course_name, "P")
print(Pstart)

[ True False False  True False]


**Q4. Consider the below student_id array:**

**Q4-1:** Reverse the **student_id** array. Print both original and reversed array.

**Q4-2:** Get the 3-largest values of **student_id** array.

In [ ]:
import numpy as np

#Q4-1
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])
student_id2 = student_id[::-1]
print(student_id)
print(student_id2)

[1023 5202 6230 1671 1682 5241 4532]
[4532 5241 1682 1671 6230 5202 1023]


In [ ]:
# Type your solution here
#Q4-2
sort = np.argsort(student_id)
result = [student_id[sort][-3:]]
print(result)

[array([5202, 5241, 6230])]


# **Q5: Write a numpy program to print sum of all the multiples of 3 or 5 below 100**

In [ ]:
# Type your solution here

# Hint: you can use arange to start off

range = np.arange(1, 100)
multiple = range[(range % 3 == 0) | (range % 5 == 0)]
print(multiple[:1000])
print(multiple.sum())

[ 3  5  6  9 10 12 15 18 20 21 24 25 27 30 33 35 36 39 40 42 45 48 50 51
 54 55 57 60 63 65 66 69 70 72 75 78 80 81 84 85 87 90 93 95 96 99]
2318


**Q6. Consider the below array.**

Q6.1. Write a code to swap column 1 with column 2.

Q6.2. Write a code to swap row 0 with row 1.

In [ ]:
import numpy as np

arr = np.arange(12).reshape(3,4)
arr[:, [1, 0]] = arr[:, [0, 1]] 
print(arr)

[[ 1  0  2  3]
 [ 5  4  6  7]
 [ 9  8 10 11]]


In [ ]:
# Type your solution here
arr = np.arange(12).reshape(3,4)
arr[[1,0],:] = arr[[0,1],: ] 
print(arr)

[[ 4  5  6  7]
 [ 0  1  2  3]
 [ 8  9 10 11]]
